In [177]:
import numpy as np
def JtM(Jones):
    A = 1/np.sqrt(2)*np.mat([[1, 0, 0, 1], [1, 0, 0, -1], [0, 1, 1, 0], [0, 1j, -1j, 0]])
    kron = np.kron(Jones, np.conj(Jones))
    M = A * kron * A.H
    
    return M.real

linear_h = np.mat([[1, 0], [0, 0]])
linear_v = np.mat([[0, 0], [0, 1]])
linear_p45 = .5 * np.mat([[1, 1], [1, 1]])
linear_n45 = .5 * np.mat([[1, -1], [-1, 1]])
rcp = .5 * np.mat([[1, 1j], [-1j, 1]])
lcp = .5 * np.mat([[1, -1j], [1j, 1]])

qwp_v = np.exp(1j*np.pi/4)*np.mat([[1, 0], [0, -1j]])
qwp_h = np.exp(1j*np.pi/4)*np.mat([[1, 0], [0, 1j]])

In [180]:
JtM(lcp)

matrix([[ 0.5,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ],
        [ 0.5,  0. ,  0. ,  0.5]])

matrix([[ 0.70710678+0.j        ,  0.00000000+0.j        ,
          0.00000000+0.j        ,  0.70710678+0.j        ],
        [ 0.70710678-0.j        , -0.00000000+0.j        ,
         -0.00000000+0.j        , -0.70710678+0.j        ],
        [ 0.00000000+0.j        ,  0.70710678+0.j        ,
          0.70710678+0.j        ,  0.00000000+0.j        ],
        [ 0.00000000+0.j        ,  0.00000000+0.70710678j,
         -0.00000000-0.70710678j,  0.00000000+0.j        ]])

In [141]:
A = 1/np.sqrt(2) * np.mat([[1, 0, 0, 1], 
            [1, 0, 0, -1], 
            [0, 1, 1, 0], 
            [0, 1j, -1j, 0]])
kron = np.kron(lcp, np.conj(lcp))
mat = A * kron * np.linalg.pinv(A)
mat.round(1)

matrix([[ 0.5+0.j,  0.0+0.j,  0.0+0.j,  0.5+0.j],
        [ 0.0+0.j,  0.0+0.j,  0.0+0.j,  0.0+0.j],
        [ 0.0+0.j,  0.0+0.j,  0.0+0.j,  0.0+0.j],
        [ 0.5+0.j,  0.0+0.j,  0.0+0.j,  0.5+0.j]])

In [121]:
A.

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]], dtype=bool)

In [125]:
A.I

matrix([[ 0.70710678+0.j        ,  0.70710678+0.j        ,
          0.00000000+0.j        ,  0.00000000+0.j        ],
        [ 0.00000000+0.j        ,  0.00000000+0.j        ,
          0.70710678+0.j        ,  0.00000000-0.70710678j],
        [ 0.00000000+0.j        ,  0.00000000+0.j        ,
          0.70710678+0.j        ,  0.00000000+0.70710678j],
        [ 0.70710678+0.j        , -0.70710678-0.j        ,
          0.00000000-0.j        ,  0.00000000-0.j        ]])